export const PARTS = 4;
export const LAST_PART_OF_FIRST_HALF = PARTS / 2;

export const MAIN_CLOCK_ID = 'MC';
export const INITIAL_MINUTES = 10;
export const DECIMALED_MINUTES = 1;

export const SHOT_CLOCK_ID = 'SC';
export const INITIAL_SHOT_CLOCK_SECONDS = 24;
export const DECIMALED_SHOT_CLOCK_SECONDS = 5;

export const TIMEOUTS_PER_FIRST_HALF = 2;
export const TIMEOUTS_PER_SECOND_HALF = 3;

export const FREE_THROWS_BY_UNSPORTSMANLIKE_OR_DISQUALIFYING_FOUL = 2;
export const FREE_THROWS_BY_FOUL_WHEN_FAILED_FIELD_BASKET = 1;